import { db, pool, countriesTable, type InsertCountry } from "@workspace/db";

const baselineCountries: InsertCountry[] = [
  {
    code: "AR",
    name: "Argentina",
    continent: "South America",
    region: "Southern Cone",
    capital: "Buenos Aires",
    flagUrl: "https://flagcdn.com/w80/ar.png",
    coverImageUrl: "https://images.unsplash.com/photo-1589909202802-8f4aadce1849?auto=format&fit=crop&w=1200&q=80",
    summary: "A South American nation shaped by Indigenous heritage, European migration, tango, literature, football, and wide regional landscapes.",
    population: 46000000,
    areaKm2: 2780400,
    languages: "Spanish, Indigenous languages",
    currency: "Argentine peso",
    governmentType: "Federal presidential republic",
    religion: "Christianity",
    featured: true,
  },
  {
    code: "AU",
    name: "Australia",
    continent: "Oceania",
    region: "Australia and New Zealand",
    capital: "Canberra",
    flagUrl: "https://flagcdn.com/w80/au.png",
    coverImageUrl: "https://images.unsplash.com/photo-1523482580672-f109ba8cb9be?auto=format&fit=crop&w=1200&q=80",
    summary: "A continent-country with ancient Aboriginal cultures, coastal cities, desert interiors, and deep connections across the Pacific.",
    population: 27000000,
    areaKm2: 7692024,
    languages: "English, Aboriginal languages",
    currency: "Australian dollar",
    governmentType: "Federal parliamentary constitutional monarchy",
    religion: "Christianity, Islam, Buddhism, Hinduism, Judaism",
    featured: true,
  },
  {
    code: "BR",
    name: "Brazil",
    continent: "South America",
    region: "South America",
    capital: "Brasilia",
    flagUrl: "https://flagcdn.com/w80/br.png",
    coverImageUrl: "https://images.unsplash.com/photo-1483729558449-99ef09a8c325?auto=format&fit=crop&w=1200&q=80",
    summary: "A vast Portuguese-speaking country known for Afro-Brazilian culture, Indigenous communities, Amazon biodiversity, music, and football.",
    population: 203000000,
    areaKm2: 8515767,
    languages: "Portuguese, Indigenous languages",
    currency: "Brazilian real",
    governmentType: "Federal presidential republic",
    religion: "Christianity, Afro-Brazilian religions",
    featured: true,
  },
  {
    code: "CA",
    name: "Canada",
    continent: "North America",
    region: "Northern America",
    capital: "Ottawa",
    flagUrl: "https://flagcdn.com/w80/ca.png",
    coverImageUrl: "https://images.unsplash.com/photo-1503614472-8c93d56e92ce?auto=format&fit=crop&w=1200&q=80",
    summary: "A northern country shaped by First Nations, Inuit, Metis, French and English heritage, immigration, and expansive landscapes.",
    population: 41000000,
    areaKm2: 9984670,
    languages: "English, French, Indigenous languages",
    currency: "Canadian dollar",
    governmentType: "Federal parliamentary constitutional monarchy",
    religion: "Christianity, Islam, Judaism, Buddhism, Hinduism",
    featured: true,
  },
  {
    code: "CN",
    name: "China",
    continent: "Asia",
    region: "East Asia",
    capital: "Beijing",
    flagUrl: "https://flagcdn.com/w80/cn.png",
    coverImageUrl: "https://images.unsplash.com/photo-1508804185872-d7badad00f7d?auto=format&fit=crop&w=1200&q=80",
    summary: "An East Asian civilization with many languages and regional traditions, long literary history, philosophy, foodways, and global influence.",
    population: 1410000000,
    areaKm2: 9596961,
    languages: "Chinese, Mandarin, Cantonese, regional languages",
    currency: "Renminbi",
    governmentType: "Unitary socialist republic",
    religion: "Buddhism, Taoism, Islam, Christianity, folk religions",
    featured: true,
  },
  {
    code: "EG",
    name: "Egypt",
    continent: "Africa",
    region: "North Africa",
    capital: "Cairo",
    flagUrl: "https://flagcdn.com/w80/eg.png",
    coverImageUrl: "https://images.unsplash.com/photo-1539768942893-daf53e448371?auto=format&fit=crop&w=1200&q=80",
    summary: "A Nile Valley country with ancient monuments, Arabic culture, Coptic heritage, Islamic scholarship, and a central role in regional history.",
    population: 112000000,
    areaKm2: 1002450,
    languages: "Arabic",
    currency: "Egyptian pound",
    governmentType: "Presidential republic",
    religion: "Islam, Christianity",
    featured: true,
  },
  {
    code: "ET",
    name: "Ethiopia",
    continent: "Africa",
    region: "East Africa",
    capital: "Addis Ababa",
    flagUrl: "https://flagcdn.com/w80/et.png",
    coverImageUrl: "https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?auto=format&fit=crop&w=1200&q=80",
    summary: "A Horn of Africa country with ancient Christian traditions, Islamic heritage, many languages, highland cultures, and deep historical continuity.",
    population: 126000000,
    areaKm2: 1104300,
    languages: "Amharic, Oromo, Tigrinya, Somali, Afar",
    currency: "Ethiopian birr",
    governmentType: "Federal parliamentary republic",
    religion: "Christianity, Islam",
    featured: false,
  },
  {
    code: "FR",
    name: "France",
    continent: "Europe",
    region: "Western Europe",
    capital: "Paris",
    flagUrl: "https://flagcdn.com/w80/fr.png",
    coverImageUrl: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1200&q=80",
    summary: "A European country known for French language, regional cultures, cuisine, philosophy, art, secular institutions, and global connections.",
    population: 68000000,
    areaKm2: 551695,
    languages: "French, regional languages",
    currency: "Euro",
    governmentType: "Semi-presidential republic",
    religion: "Christianity, Islam, Judaism, Buddhism",
    featured: false,
  },
  {
    code: "DE",
    name: "Germany",
    continent: "Europe",
    region: "Western Europe",
    capital: "Berlin",
    flagUrl: "https://flagcdn.com/w80/de.png",
    coverImageUrl: "https://images.unsplash.com/photo-1467269204594-9661b134dd2b?auto=format&fit=crop&w=1200&q=80",
    summary: "A central European country with diverse regional identities, German language traditions, engineering, music, philosophy, and federal civic life.",
    population: 84000000,
    areaKm2: 357022,
    languages: "German",
    currency: "Euro",
    governmentType: "Federal parliamentary republic",
    religion: "Christianity, Islam, Judaism",
    featured: false,
  },
  {
    code: "IN",
    name: "India",
    continent: "Asia",
    region: "South Asia",
    capital: "New Delhi",
    flagUrl: "https://flagcdn.com/w80/in.png",
    coverImageUrl: "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=1200&q=80",
    summary: "A multilingual South Asian country with layered Hindu, Muslim, Sikh, Buddhist, Jain, Christian, tribal, and regional traditions.",
    population: 1430000000,
    areaKm2: 3287263,
    languages: "Hindi, English, Bengali, Tamil, Telugu, Marathi, Urdu",
    currency: "Indian rupee",
    governmentType: "Federal parliamentary republic",
    religion: "Hinduism, Islam, Christianity, Sikhism, Buddhism, Jainism",
    featured: true,
  },
  {
    code: "ID",
    name: "Indonesia",
    continent: "Asia",
    region: "Southeast Asia",
    capital: "Jakarta",
    flagUrl: "https://flagcdn.com/w80/id.png",
    coverImageUrl: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=1200&q=80",
    summary: "An archipelagic Southeast Asian country with hundreds of languages, island cultures, Islamic traditions, and rich biodiversity.",
    population: 280000000,
    areaKm2: 1904569,
    languages: "Indonesian, Javanese, Sundanese, regional languages",
    currency: "Indonesian rupiah",
    governmentType: "Presidential republic",
    religion: "Islam, Christianity, Hinduism, Buddhism",
    featured: false,
  },
  {
    code: "IL",
    name: "Israel",
    continent: "Asia",
    region: "Middle East",
    capital: "Jerusalem",
    flagUrl: "https://flagcdn.com/w80/il.png",
    coverImageUrl: "https://images.unsplash.com/photo-1542743408-218cc173cda0?auto=format&fit=crop&w=1200&q=80",
    summary: "A Middle Eastern country with Hebrew and Arabic communities, Jewish history, Muslim and Christian heritage, and many immigrant traditions.",
    population: 10000000,
    areaKm2: 22072,
    languages: "Hebrew, Arabic, English, Russian",
    currency: "Israeli new shekel",
    governmentType: "Parliamentary republic",
    religion: "Judaism, Islam, Christianity, Druze",
    featured: false,
  },
  {
    code: "JP",
    name: "Japan",
    continent: "Asia",
    region: "East Asia",
    capital: "Tokyo",
    flagUrl: "https://flagcdn.com/w80/jp.png",
    coverImageUrl: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=1200&q=80",
    summary: "An East Asian island country known for Japanese language, Shinto and Buddhist heritage, design, technology, food, and regional festivals.",
    population: 124000000,
    areaKm2: 377975,
    languages: "Japanese",
    currency: "Japanese yen",
    governmentType: "Parliamentary constitutional monarchy",
    religion: "Shinto, Buddhism, Christianity",
    featured: true,
  },
  {
    code: "KE",
    name: "Kenya",
    continent: "Africa",
    region: "East Africa",
    capital: "Nairobi",
    flagUrl: "https://flagcdn.com/w80/ke.png",
    coverImageUrl: "https://images.unsplash.com/photo-1489392191049-fc10c97e64b6?auto=format&fit=crop&w=1200&q=80",
    summary: "An East African country with Swahili and English public life, many communities, coastal trade heritage, highlands, and savannas.",
    population: 55000000,
    areaKm2: 580367,
    languages: "Swahili, English, Kikuyu, Luo, Luhya, Kalenjin",
    currency: "Kenyan shilling",
    governmentType: "Presidential republic",
    religion: "Christianity, Islam, Indigenous beliefs",
    featured: false,
  },
  {
    code: "MX",
    name: "Mexico",
    continent: "North America",
    region: "Latin America",
    capital: "Mexico City",
    flagUrl: "https://flagcdn.com/w80/mx.png",
    coverImageUrl: "https://images.unsplash.com/photo-1518105779142-d975f22f1b0a?auto=format&fit=crop&w=1200&q=80",
    summary: "A North American country with Indigenous civilizations, Spanish language, regional cultures, music, foodways, and diasporic ties.",
    population: 130000000,
    areaKm2: 1964375,
    languages: "Spanish, Nahuatl, Maya languages, Indigenous languages",
    currency: "Mexican peso",
    governmentType: "Federal presidential republic",
    religion: "Christianity, Indigenous traditions",
    featured: true,
  },
  {
    code: "NG",
    name: "Nigeria",
    continent: "Africa",
    region: "West Africa",
    capital: "Abuja",
    flagUrl: "https://flagcdn.com/w80/ng.png",
    coverImageUrl: "https://images.unsplash.com/photo-1522547902298-51566e4fb383?auto=format&fit=crop&w=1200&q=80",
    summary: "A West African country with hundreds of languages and communities, including Yoruba, Hausa, Igbo, Fulani, and many others.",
    population: 224000000,
    areaKm2: 923768,
    languages: "English, Hausa, Yoruba, Igbo, Fulfulde",
    currency: "Nigerian naira",
    governmentType: "Federal presidential republic",
    religion: "Islam, Christianity, Indigenous beliefs",
    featured: true,
  },
  {
    code: "PK",
    name: "Pakistan",
    continent: "Asia",
    region: "South Asia",
    capital: "Islamabad",
    flagUrl: "https://flagcdn.com/w80/pk.png",
    coverImageUrl: "https://images.unsplash.com/photo-1625472603517-1b0dc72846ab?auto=format&fit=crop&w=1200&q=80",
    summary: "A South Asian country with Urdu, Punjabi, Sindhi, Pashto, Balochi, and many other cultural and linguistic traditions.",
    population: 241000000,
    areaKm2: 881913,
    languages: "Urdu, English, Punjabi, Sindhi, Pashto, Balochi",
    currency: "Pakistani rupee",
    governmentType: "Federal parliamentary republic",
    religion: "Islam, Christianity, Hinduism, Sikhism",
    featured: false,
  },
  {
    code: "PH",
    name: "Philippines",
    continent: "Asia",
    region: "Southeast Asia",
    capital: "Manila",
    flagUrl: "https://flagcdn.com/w80/ph.png",
    coverImageUrl: "https://images.unsplash.com/photo-1518509562904-e7ef99cdcc86?auto=format&fit=crop&w=1200&q=80",
    summary: "A Southeast Asian archipelago with Filipino and regional languages, Indigenous communities, Catholic heritage, Islam, and island cultures.",
    population: 117000000,
    areaKm2: 300000,
    languages: "Filipino, English, Cebuano, Ilocano, regional languages",
    currency: "Philippine peso",
    governmentType: "Presidential republic",
    religion: "Christianity, Islam, Indigenous beliefs",
    featured: false,
  },
  {
    code: "ZA",
    name: "South Africa",
    continent: "Africa",
    region: "Southern Africa",
    capital: "Pretoria, Cape Town, Bloemfontein",
    flagUrl: "https://flagcdn.com/w80/za.png",
    coverImageUrl: "https://images.unsplash.com/photo-1484318571209-661cf29a69eb?auto=format&fit=crop&w=1200&q=80",
    summary: "A southern African country with many official languages, diverse communities, anti-apartheid history, and vibrant cultural life.",
    population: 62000000,
    areaKm2: 1221037,
    languages: "Zulu, Xhosa, Afrikaans, English, Sesotho, Setswana",
    currency: "South African rand",
    governmentType: "Parliamentary republic",
    religion: "Christianity, Islam, Hinduism, Judaism, Indigenous beliefs",
    featured: true,
  },
  {
    code: "KR",
    name: "South Korea",
    continent: "Asia",
    region: "East Asia",
    capital: "Seoul",
    flagUrl: "https://flagcdn.com/w80/kr.png",
    coverImageUrl: "https://images.unsplash.com/photo-1538485399081-7191377e8241?auto=format&fit=crop&w=1200&q=80",
    summary: "An East Asian country with Korean language, Confucian and Buddhist legacies, modern creative industries, technology, and family traditions.",
    population: 52000000,
    areaKm2: 100210,
    languages: "Korean",
    currency: "South Korean won",
    governmentType: "Presidential republic",
    religion: "Christianity, Buddhism, Confucian traditions",
    featured: false,
  },
  {
    code: "ES",
    name: "Spain",
    continent: "Europe",
    region: "Southern Europe",
    capital: "Madrid",
    flagUrl: "https://flagcdn.com/w80/es.png",
    coverImageUrl: "https://images.unsplash.com/photo-1509840841025-9088ba78a826?auto=format&fit=crop&w=1200&q=80",
    summary: "A southern European country with Spanish, Catalan, Basque, Galician, Andalusian, Islamic, Jewish, and Mediterranean influences.",
    population: 48000000,
    areaKm2: 505990,
    languages: "Spanish, Catalan, Basque, Galician",
    currency: "Euro",
    governmentType: "Parliamentary constitutional monarchy",
    religion: "Christianity, Islam, Judaism",
    featured: false,
  },
  {
    code: "TR",
    name: "Turkey",
    continent: "Asia",
    region: "Middle East and Anatolia",
    capital: "Ankara",
    flagUrl: "https://flagcdn.com/w80/tr.png",
    coverImageUrl: "https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?auto=format&fit=crop&w=1200&q=80",
    summary: "A transcontinental country connecting Anatolia, the Balkans, the Black Sea, and the Mediterranean through layered cultural history.",
    population: 85000000,
    areaKm2: 783562,
    languages: "Turkish, Kurdish, Arabic, regional languages",
    currency: "Turkish lira",
    governmentType: "Presidential republic",
    religion: "Islam, Christianity, Judaism",
    featured: false,
  },
  {
    code: "GB",
    name: "United Kingdom",
    continent: "Europe",
    region: "Northern Europe",
    capital: "London",
    flagUrl: "https://flagcdn.com/w80/gb.png",
    coverImageUrl: "https://images.unsplash.com/photo-1486299267070-83823f5448dd?auto=format&fit=crop&w=1200&q=80",
    summary: "A European island state made up of England, Scotland, Wales, and Northern Ireland, with many regional identities and languages.",
    population: 68000000,
    areaKm2: 243610,
    languages: "English, Welsh, Scottish Gaelic, Irish, Scots",
    currency: "Pound sterling",
    governmentType: "Parliamentary constitutional monarchy",
    religion: "Christianity, Islam, Hinduism, Sikhism, Judaism, Buddhism",
    featured: false,
  },
  {
    code: "US",
    name: "United States",
    continent: "North America",
    region: "Northern America",
    capital: "Washington, D.C.",
    flagUrl: "https://flagcdn.com/w80/us.png",
    coverImageUrl: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80",
    summary: "A North American country shaped by Indigenous nations, migration, African American history, regional cultures, civic ideals, and global exchange.",
    population: 335000000,
    areaKm2: 9833517,
    languages: "English, Spanish, Indigenous languages, many immigrant languages",
    currency: "United States dollar",
    governmentType: "Federal presidential republic",
    religion: "Christianity, Judaism, Islam, Buddhism, Hinduism, Indigenous traditions",
    featured: true,
  },
];

async function main() {
  const targetUrl = process.env.DATABASE_URL ?? "";
  if (!targetUrl) {
    throw new Error("DATABASE_URL must be set before seeding countries.");
  }

  const host = new URL(targetUrl).hostname;
  console.log(`Preparing to upsert ${baselineCountries.length} baseline countries into host: ${host}`);

  await db.transaction(async (tx) => {
    for (const country of baselineCountries) {
      await tx
        .insert(countriesTable)
        .values(country)
        .onConflictDoUpdate({
          target: countriesTable.code,
          set: {
            name: country.name,
            continent: country.continent,
            region: country.region ?? null,
            capital: country.capital ?? null,
            flagUrl: country.flagUrl ?? null,
            coverImageUrl: country.coverImageUrl ?? null,
            summary: country.summary ?? null,
            population: country.population ?? null,
            areaKm2: country.areaKm2 ?? null,
            languages: country.languages ?? null,
            currency: country.currency ?? null,
            governmentType: country.governmentType ?? null,
            religion: country.religion ?? null,
            featured: country.featured ?? false,
          },
        });
    }
  });

  console.log(`Upserted ${baselineCountries.length} baseline countries.`);
  await pool.end();
}

main().catch(async (err) => {
  console.error(err);
  await pool.end();
  process.exit(1);
});
